services:
  nats:
    image: nats:2.10-alpine
    container_name: iot-nats-server
    ports:
      - "4222:4222"    # NATS client port
      - "8222:8222"    # HTTP monitoring port
      - "1883:1883"    # MQTT port
    volumes:
      - ./infrastructure/nats/nats-working.conf:/nats-server.conf:ro
    command: ["--config", "/nats-server.conf"]
    networks:
      - iot-server-smart-irrigation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/varz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: pgvector/pgvector:pg15
    container_name: iot-postgres-vector
    environment:
      POSTGRES_DB: smart-irrigation-system-db
      POSTGRES_USER: liwaisi-sis-admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      postgres 
      -c shared_buffers=512MB
      -c work_mem=32MB
      -c maintenance_work_mem=256MB
      -c effective_cache_size=1536MB
      -c max_connections=200
      -c log_min_duration_statement=1000
      -c log_statement=none
    networks:
      - iot-server-smart-irrigation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liwaisi-sis-admin -d smart-irrigation-system-db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    shm_size: 2gb
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
          cpus: '1'

  go-soc-consumer:
    build:
      context: ./backend/go-soc-consumer
      dockerfile: Dockerfile
    container_name: iot-go-soc-consumer
    environment:
      # Database Configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: liwaisi-sis-admin
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DB_NAME: smart-irrigation-system-db
      DB_SSL_MODE: disable
      DB_MAX_OPEN_CONNS: 25
      DB_MAX_IDLE_CONNS: 5
      DB_CONN_MAX_LIFETIME: 5m
      DB_CONN_MAX_IDLE_TIME: 1m
      # MQTT Configuration
      MQTT_BROKER_URL: tcp://nats:1883
      MQTT_CLIENT_ID: iot-go-soc-consumer
      MQTT_USERNAME: ""
      MQTT_PASSWORD: ""
      MQTT_PORT: 1883
      # NATS Configuration
      NATS_URL: nats://nats:4222
      NATS_CLIENT_ID: iot-go-soc-consumer
      NATS_SUBJECT_PREFIX: liwaisi.iot.smart-irrigation
      # Application Configuration
      HTTP_PORT: 8080
      HTTP_HOST: 0.0.0.0
      LOG_LEVEL: info
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy
    networks:
      - iot-server-smart-irrigation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  iot-server-smart-irrigation-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  nats_data:
    driver: local
  postgres_data:
    driver: local