logger:
  level: "info"
  environment: "production"
  encoding: "json"
  output_paths:
    - "stdout"

mqtt:
  broker:
    host: "localhost"
    port: 1883
    protocol: "tcp"  # tcp, ws, wss, ssl, tls
  client:
    client_id: "go-consumer-sis"
    clean_session: true
    auto_reconnect: true
    keep_alive: 60
    ping_timeout: 10s
    connect_timeout: 30s
    write_timeout: 30s
    resume_subs: true
  auth:
    username: ""
    password: ""
    cert_file: ""
    key_file: ""
  tls:
    enabled: false
    ca_file: ""
    cert_file: ""
    key_file: ""
    insecure_skip_verify: false
    server_name: ""
  connection:
    max_reconnect_interval: 10m
    reconnect_backoff: 1s
    max_reconnect_backoff: 10s
    connect_retry: true
    connect_retry_interval: 30s
  subscriptions:
    - topic: "/+/iot/smart-irrigation/device/registration"
      qos: 1
      handler: "device_registration"
  quality_of_service:
    default_qos: 1
    max_qos: 2
    retain_available: true
    retain_handling: 0  # 0=send retained messages, 1=send if subscription doesn't exist, 2=don't send
  message_handling:
    max_inflight: 100
    message_channel_depth: 1000
    error_handler: "log"  # log, ignore, panic

database:
  host: "localhost"
  port: 5432
  user: "liwaisi-sis-admin"
  password: "postgres"
  dbname: "smart-irrigation-system-db"
  sslmode: "disable"
  max_connections: 25
  max_idle_connections: 5

handlers:
  device_registration:
    workers: 2
    buffer_size: 10