// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/liwaisi-tech/iot-server-smart-irrigation/backend/go-soc-consumer/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeviceHealthUseCase creates a new instance of MockDeviceHealthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceHealthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceHealthUseCase {
	mock := &MockDeviceHealthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeviceHealthUseCase is an autogenerated mock type for the DeviceHealthUseCase type
type MockDeviceHealthUseCase struct {
	mock.Mock
}

type MockDeviceHealthUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceHealthUseCase) EXPECT() *MockDeviceHealthUseCase_Expecter {
	return &MockDeviceHealthUseCase_Expecter{mock: &_m.Mock}
}

// ProcessDeviceDetectedEvent provides a mock function for the type MockDeviceHealthUseCase
func (_mock *MockDeviceHealthUseCase) ProcessDeviceDetectedEvent(ctx context.Context, event *entities.DeviceDetectedEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for ProcessDeviceDetectedEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.DeviceDetectedEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceHealthUseCase_ProcessDeviceDetectedEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessDeviceDetectedEvent'
type MockDeviceHealthUseCase_ProcessDeviceDetectedEvent_Call struct {
	*mock.Call
}

// ProcessDeviceDetectedEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event *entities.DeviceDetectedEvent
func (_e *MockDeviceHealthUseCase_Expecter) ProcessDeviceDetectedEvent(ctx interface{}, event interface{}) *MockDeviceHealthUseCase_ProcessDeviceDetectedEvent_Call {
	return &MockDeviceHealthUseCase_ProcessDeviceDetectedEvent_Call{Call: _e.mock.On("ProcessDeviceDetectedEvent", ctx, event)}
}

func (_c *MockDeviceHealthUseCase_ProcessDeviceDetectedEvent_Call) Run(run func(ctx context.Context, event *entities.DeviceDetectedEvent)) *MockDeviceHealthUseCase_ProcessDeviceDetectedEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.DeviceDetectedEvent
		if args[1] != nil {
			arg1 = args[1].(*entities.DeviceDetectedEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceHealthUseCase_ProcessDeviceDetectedEvent_Call) Return(err error) *MockDeviceHealthUseCase_ProcessDeviceDetectedEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceHealthUseCase_ProcessDeviceDetectedEvent_Call) RunAndReturn(run func(ctx context.Context, event *entities.DeviceDetectedEvent) error) *MockDeviceHealthUseCase_ProcessDeviceDetectedEvent_Call {
	_c.Call.Return(run)
	return _c
}
