// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockEventPublisher
func (_mock *MockEventPublisher) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventPublisher_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockEventPublisher_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEventPublisher_Expecter) Close(ctx interface{}) *MockEventPublisher_Close_Call {
	return &MockEventPublisher_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockEventPublisher_Close_Call) Run(run func(ctx context.Context)) *MockEventPublisher_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventPublisher_Close_Call) Return(err error) *MockEventPublisher_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventPublisher_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockEventPublisher_Close_Call {
	_c.Call.Return(run)
	return _c
}

// IsConnected provides a mock function for the type MockEventPublisher
func (_mock *MockEventPublisher) IsConnected() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsConnected")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockEventPublisher_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type MockEventPublisher_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
func (_e *MockEventPublisher_Expecter) IsConnected() *MockEventPublisher_IsConnected_Call {
	return &MockEventPublisher_IsConnected_Call{Call: _e.mock.On("IsConnected")}
}

func (_c *MockEventPublisher_IsConnected_Call) Run(run func()) *MockEventPublisher_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventPublisher_IsConnected_Call) Return(b bool) *MockEventPublisher_IsConnected_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockEventPublisher_IsConnected_Call) RunAndReturn(run func() bool) *MockEventPublisher_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockEventPublisher
func (_mock *MockEventPublisher) Publish(ctx context.Context, subject string, data interface{}) error {
	ret := _mock.Called(ctx, subject, data)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = returnFunc(ctx, subject, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockEventPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - subject string
//   - data interface{}
func (_e *MockEventPublisher_Expecter) Publish(ctx interface{}, subject interface{}, data interface{}) *MockEventPublisher_Publish_Call {
	return &MockEventPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, subject, data)}
}

func (_c *MockEventPublisher_Publish_Call) Run(run func(ctx context.Context, subject string, data interface{})) *MockEventPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 interface{}
		if args[2] != nil {
			arg2 = args[2].(interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventPublisher_Publish_Call) Return(err error) *MockEventPublisher_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventPublisher_Publish_Call) RunAndReturn(run func(ctx context.Context, subject string, data interface{}) error) *MockEventPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}
