// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPingUseCase creates a new instance of MockPingUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPingUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPingUseCase {
	mock := &MockPingUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPingUseCase is an autogenerated mock type for the PingUseCase type
type MockPingUseCase struct {
	mock.Mock
}

type MockPingUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPingUseCase) EXPECT() *MockPingUseCase_Expecter {
	return &MockPingUseCase_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type MockPingUseCase
func (_mock *MockPingUseCase) Ping(ctx context.Context) string {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockPingUseCase_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockPingUseCase_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPingUseCase_Expecter) Ping(ctx interface{}) *MockPingUseCase_Ping_Call {
	return &MockPingUseCase_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockPingUseCase_Ping_Call) Run(run func(ctx context.Context)) *MockPingUseCase_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPingUseCase_Ping_Call) Return(s string) *MockPingUseCase_Ping_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockPingUseCase_Ping_Call) RunAndReturn(run func(ctx context.Context) string) *MockPingUseCase_Ping_Call {
	_c.Call.Return(run)
	return _c
}
