// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/liwaisi-tech/iot-server-smart-irrigation/backend/go-soc-consumer/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSensorDataUseCase creates a new instance of MockSensorDataUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSensorDataUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSensorDataUseCase {
	mock := &MockSensorDataUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSensorDataUseCase is an autogenerated mock type for the SensorDataUseCase type
type MockSensorDataUseCase struct {
	mock.Mock
}

type MockSensorDataUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSensorDataUseCase) EXPECT() *MockSensorDataUseCase_Expecter {
	return &MockSensorDataUseCase_Expecter{mock: &_m.Mock}
}

// StoreSensorData provides a mock function for the type MockSensorDataUseCase
func (_mock *MockSensorDataUseCase) StoreSensorData(ctx context.Context, data *entities.SensorTemperatureHumidity) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for StoreSensorData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.SensorTemperatureHumidity) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSensorDataUseCase_StoreSensorData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreSensorData'
type MockSensorDataUseCase_StoreSensorData_Call struct {
	*mock.Call
}

// StoreSensorData is a helper method to define mock.On call
//   - ctx context.Context
//   - data *entities.SensorTemperatureHumidity
func (_e *MockSensorDataUseCase_Expecter) StoreSensorData(ctx interface{}, data interface{}) *MockSensorDataUseCase_StoreSensorData_Call {
	return &MockSensorDataUseCase_StoreSensorData_Call{Call: _e.mock.On("StoreSensorData", ctx, data)}
}

func (_c *MockSensorDataUseCase_StoreSensorData_Call) Run(run func(ctx context.Context, data *entities.SensorTemperatureHumidity)) *MockSensorDataUseCase_StoreSensorData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.SensorTemperatureHumidity
		if args[1] != nil {
			arg1 = args[1].(*entities.SensorTemperatureHumidity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSensorDataUseCase_StoreSensorData_Call) Return(err error) *MockSensorDataUseCase_StoreSensorData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSensorDataUseCase_StoreSensorData_Call) RunAndReturn(run func(ctx context.Context, data *entities.SensorTemperatureHumidity) error) *MockSensorDataUseCase_StoreSensorData_Call {
	_c.Call.Return(run)
	return _c
}
