// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/liwaisi-tech/iot-server-smart-irrigation/backend/go-soc-consumer/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSensorTemperatureHumidityRepository creates a new instance of MockSensorTemperatureHumidityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSensorTemperatureHumidityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSensorTemperatureHumidityRepository {
	mock := &MockSensorTemperatureHumidityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSensorTemperatureHumidityRepository is an autogenerated mock type for the SensorTemperatureHumidityRepository type
type MockSensorTemperatureHumidityRepository struct {
	mock.Mock
}

type MockSensorTemperatureHumidityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSensorTemperatureHumidityRepository) EXPECT() *MockSensorTemperatureHumidityRepository_Expecter {
	return &MockSensorTemperatureHumidityRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSensorTemperatureHumidityRepository
func (_mock *MockSensorTemperatureHumidityRepository) Create(ctx context.Context, sensorData *entities.SensorTemperatureHumidity) error {
	ret := _mock.Called(ctx, sensorData)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.SensorTemperatureHumidity) error); ok {
		r0 = returnFunc(ctx, sensorData)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSensorTemperatureHumidityRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSensorTemperatureHumidityRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sensorData *entities.SensorTemperatureHumidity
func (_e *MockSensorTemperatureHumidityRepository_Expecter) Create(ctx interface{}, sensorData interface{}) *MockSensorTemperatureHumidityRepository_Create_Call {
	return &MockSensorTemperatureHumidityRepository_Create_Call{Call: _e.mock.On("Create", ctx, sensorData)}
}

func (_c *MockSensorTemperatureHumidityRepository_Create_Call) Run(run func(ctx context.Context, sensorData *entities.SensorTemperatureHumidity)) *MockSensorTemperatureHumidityRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.SensorTemperatureHumidity
		if args[1] != nil {
			arg1 = args[1].(*entities.SensorTemperatureHumidity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSensorTemperatureHumidityRepository_Create_Call) Return(err error) *MockSensorTemperatureHumidityRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSensorTemperatureHumidityRepository_Create_Call) RunAndReturn(run func(ctx context.Context, sensorData *entities.SensorTemperatureHumidity) error) *MockSensorTemperatureHumidityRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
