all: false
dir: "{{.InterfaceDir}}"
filename: "mocks_test.go"
force-file-write: false
formatter: goimports
log-level: info
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
recursive: false
template: testify
packages:
  github.com/liwaisi/iot-server-smart-irrigation/services/go-consumers/internal/domain/repositories:
    config:
      all: true
      dir: "./mocks/repositories"
      filename: "{{.InterfaceName}}_mock.go"
      pkgname: "mocks"
  github.com/liwaisi/iot-server-smart-irrigation/services/go-consumers/internal/domain/services:
    config:
      all: true
      dir: "./mocks/services"
      filename: "{{.InterfaceName}}_mock.go"
      pkgname: "mocks"
  github.com/liwaisi/iot-server-smart-irrigation/services/go-consumers/internal/application/services:
    config:
      all: true
      dir: "./mocks/application"
      filename: "{{.InterfaceName}}_mock.go"
      pkgname: "mocks"